<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="" tests="5" assertions="3" errors="2" warnings="0" failures="0" skipped="0" time="0.102726">
    <testsuite name="App" tests="5" assertions="3" errors="2" warnings="0" failures="0" skipped="0" time="0.102726">
      <testsuite name="ExampleDatabaseTest" file="C:\xampp\htdocs\timesheet\tests\database\ExampleDatabaseTest.php" tests="2" assertions="0" errors="2" warnings="0" failures="0" skipped="0" time="0.075218">
        <testcase name="testModelFindAll" class="ExampleDatabaseTest" classname="ExampleDatabaseTest" file="C:\xampp\htdocs\timesheet\tests\database\ExampleDatabaseTest.php" line="17" assertions="0" time="0.069795">
          <error type="CodeIgniter\Database\Exceptions\DatabaseException">ExampleDatabaseTest::testModelFindAll
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class "SQLite3" not found

C:\xampp\htdocs\timesheet\vendor\codeigniter4\framework\system\Database\BaseConnection.php:427
C:\xampp\htdocs\timesheet\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\xampp\htdocs\timesheet\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:74
C:\xampp\htdocs\timesheet\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:54
C:\xampp\htdocs\timesheet\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:248</error>
        </testcase>
        <testcase name="testSoftDeleteLeavesRow" class="ExampleDatabaseTest" classname="ExampleDatabaseTest" file="C:\xampp\htdocs\timesheet\tests\database\ExampleDatabaseTest.php" line="28" assertions="0" time="0.005423">
          <error type="CodeIgniter\Database\Exceptions\DatabaseException">ExampleDatabaseTest::testSoftDeleteLeavesRow
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class "SQLite3" not found

C:\xampp\htdocs\timesheet\vendor\codeigniter4\framework\system\Database\BaseConnection.php:427
C:\xampp\htdocs\timesheet\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\xampp\htdocs\timesheet\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:74
C:\xampp\htdocs\timesheet\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:54
C:\xampp\htdocs\timesheet\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:248</error>
        </testcase>
      </testsuite>
      <testsuite name="ExampleSessionTest" file="C:\xampp\htdocs\timesheet\tests\session\ExampleSessionTest.php" tests="1" assertions="1" errors="0" warnings="0" failures="0" skipped="0" time="0.005430">
        <testcase name="testSessionSimple" class="ExampleSessionTest" classname="ExampleSessionTest" file="C:\xampp\htdocs\timesheet\tests\session\ExampleSessionTest.php" line="11" assertions="1" time="0.005430"/>
      </testsuite>
      <testsuite name="HealthTest" file="C:\xampp\htdocs\timesheet\tests\unit\HealthTest.php" tests="2" assertions="2" errors="0" warnings="0" failures="0" skipped="0" time="0.022078">
        <testcase name="testIsDefinedAppPath" class="HealthTest" classname="HealthTest" file="C:\xampp\htdocs\timesheet\tests\unit\HealthTest.php" line="13" assertions="1" time="0.003447"/>
        <testcase name="testBaseUrlHasBeenSet" class="HealthTest" classname="HealthTest" file="C:\xampp\htdocs\timesheet\tests\unit\HealthTest.php" line="18" assertions="1" time="0.018631"/>
      </testsuite>
    </testsuite>
  </testsuite>
</testsuites>
